name: build Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        default: ubuntu:jammy
      run_platform:
        required: false
        type: string
        default: ubuntu-22.04

jobs:
  build:
    runs-on: ${{ inputs.run_platform }}
    container:
      image: ${{ inputs.image_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'

      - name: Use cmake
        run: cmake --version

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies for build
        run: |
          sudo apt install libacl1-dev curl libssl-dev -y

      - name: start build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          ./build.sh
