name: CI/CD Workflow

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'document/**'
    branches:
      - '*'
      - '**'
  push:
    branches:
      - '*'
      - '**'
  release:
    types: [published]

jobs:
  # check:
  #   uses: ./.github/workflows/cppcheck.yml
  #   with:
  #     image_name: ubuntu
  #   secrets: inherit

  test:
    uses: ./.github/workflows/test-workflow.yml
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            image: ubuntu:jammy
          - platform: ubuntu-22.04-arm
            image: ubuntu:jammy

  build_x86:
    uses: ./.github/workflows/build-workflow.yml
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            image: ubuntu:jammy
          - platform: ubuntu-22.04-arm
            image: ubuntu:jammy



