name: test Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        default: ubuntu
      run_platform:
        required: false
        type: string
        default: amd64

jobs:
  test:
    runs-on: ${{ inputs.run_platform }}
    container:
      image: ${{ inputs.image_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: download and Use cmake
        run: |
          pip install cmake --upgrade
          cmake --version

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies for build
        run: |
          sudo apt install libacl1-dev curl libssl-dev -y

      - name: start test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          ./test.sh